name: Draft release
on:
  workflow_call:
jobs:
  draft-release:
    name: Update release drafter
    permissions:
      contents: write
      pull-requests: write
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
